apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-frontend
  namespace: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-frontend
  template:
    metadata:
      labels:
        app: student-frontend
    spec:
      containers:
        - name: student-frontend
          image: student-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: student-frontend-service
  namespace: student-management
spec:
  selector:
    app: student-frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
